alg_name: "UnKE"
model_name: "./hugging_cache/llama3-8b"
stats_dir: "./data/stats"
device: 0
layers: [7]
clamp_norm_factor: 4.0
layer_selection: "all"
fact_token: "last"
lr: 2e-4
v_num_grad_steps: 25
v_lr: 5e-1
v_loss_layer: 31
v_weight_decay: 1e-3
optim_num_step: 50
ex_data_num: 20
rewrite_module_tmp: "model.layers.{}.mlp.down_proj"
layer_module_tmp: "model.layers.{}"
mlp_module_tmp: "model.layers.{}.mlp"
attn_module_tmp: "model.layers.{}.self_attn"
ln_f_module: "model.norm"
lm_head_module: "lm_head"

batch_size: 1
model_parallel: false